### PR TITLE
@akshhack you just got an offer (via @githirenow)

### PR DESCRIPTION
**Pull request by githirenow**
<h1 align=center>
    Hey @akshhack 👋, shivambhatia5432 sent you a message! (via @githirenow) 📧
  </h1>
  <p align=center>
    
  </p><h2 align=center>YOOO, testing 123</h2><h4 align=center>You can schedule a call or connect with @shivambhatia5432!</h4><p align=center><span><b>Email:</b> shivam.bhatia54321@gmail.com</span></p><p align=center><span><b>Linkedin:</b> https://www.linkedin.com/in/shivambhatia5432/</span></p><p align=center><span><b>Calendly:</b> cal.com/shivambhatia</span></p>
  <a href=githired.io>
    <p align=center>
      
    </p>
    <h4 align=center>
      <i>*This message was sent using Githired.io (@githirenow)* 💪</i>
    </h4>
  </a>
  <h5 align=center>
    🤯 Bring your project idea to life within a few clicks - it's that easy.<br />
    🤓 Find devs who've made what you're building on GitHub.<br />
    🧐 Search your idea, leverage access to top talent.
  </h5>

### CODE REVIEW

**Comment by shivambhatia5432** [comment]
Hey,
how are you?

**Comment by akshhack** [comment]
im good
Best,
Akshat Prakash
CTO, CAMB.AI
LinkedIn <https://www.linkedin.com/in/akshat-prakash/>
Calendar <https://calendly.com/akshatp-cs/chat>

Camb.ai (“We/our”) asserts that its use of name, image, or likeness in the
showcased promotional content (“content”) is for illustrative purposes only
and constitutes fair use under applicable copyright laws. We acknowledge
and respect the intellectual property rights of others, and any use of
copyrighted materials in its content is done so in accordance with fair use
principles. The content included is not intended to be an endorsement.
Our Artificial
Intelligence (“AI”) solutions/services are developed with the goal of
ensuring that they operate in a responsible and ethical manner, and in
compliance with all applicable laws and regulations to the best of our
ability. We do not guarantee that our AI solutions/services will be
completely free from any inaccuracies. However, we are committed to
continuously improving our technology to ensure that it operates in a
responsible and ethical manner.

**Comment by shivambhatia5432** [comment]
Hey @akshhack Just checking something @shivam@githired.io

**Comment by githirenow** [comment]
@***@***.*** ***@***.***>

**Comment by githirenow** [comment]
@***@***.*** ***@***.***>

**Comment by shivambhatia5432** [comment]
Checking again mailto:shivam@githired.io

**Pull request closed without merging**
